hlaseni = {
    "pozdrav": "Hi cowgirl or cowboy!",
    "uvod": "I will generat a random X-digit number for you.",
    "vyzva": "Let's play The bulls and cows game.",
    "vyzva_pocet": "Choose how many digits the number will contain.",
    "zadani_pocet": "Enter a number between 3 to 7:",
    "zadani_platny": "Enter a valid entry - only one number from 3 to 7.",
    "hadej_cislo": "Enter your guess:",
    "generovano": "I've thought a {} digit number, let's guess it.",
    "oddelovac": 78 * "-",
    "delka": "The number must contain of {} digits. Guess again.",
    "neni_cislo": "It is necessary to enter digits from 0 to 9. Guess again.",
    "unikatni": "Digits must be unique. Guess again.",
    "zacina_nulou": "The number must not start with '0'. Guess again.",
    "konec": "Thanks for playing! But sorry, I'll not tell you the number.",
    "konec_bez_cisla": "Thanks for playing! See you next time.",
    "gratulace": "!!! Congratulations !!!",
    "pokusy": "Number of attempts needed to guess: >{}<",
    "cas": "Seconds needed to guess: >{}<",
    "prumer": "Seconds per try: >{}<",
    "mereni_casu": "Press Enter to start timing..."
}